### PR TITLE
Updated Circle to use license accepted orb

### PR DESCRIPTION
**Pull request by username-is-already-taken2**
### Description

I noticed PR #22 was failing Circle CI due to license acceptance, so I've updated the circle ci config to fix that.  I'm not sure if I should have done it to the PR branch or created my own, please let me know either way

### Issues Resolved

Helps PR 22

### Contribution Check List

- [x] All tests pass.
- [ ]  ~~New functionality includes testing.~~
- [ ] ~~New functionality has been documented in the README if applicable~~

### CODE REVIEW

**Comment by Xorima** [comment]
thanks for this, if you take a look at vscode you can see the other changes required, also set the orb to @2 instead of full depth pinning please :)

**Comment by username-is-already-taken2** [comment]
Let me check through those linting issues at lunch, @Xorima will do

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by username-is-already-taken2** [comment]
@Xorima - ci delivery and danger are now passing after the linting corrections, I'm not to sure where it's referencing 'ci/circle: lint' within the PR checks section as I renamed the lint task to use the delivery one in the new orb.

**Comment by Xorima** [comment]
this is a setting elsewhere, I can get this sorted tonight, can you resolve the dangerfile issues as well please?

**Comment by JohnRoesler** [comment]
That is managed via terraform [control_groups](https://github.com/sous-chefs/terraform-github-org/blob/master/control_groups.tf) you'd need add [this line](https://github.com/sous-chefs/terraform-github-org/blob/master/haproxy.tf#L7) as the `default = ["ci/circleci: lint"]`

**Pull request merged**
