### PR TITLE
Added missing closing bracket

### PR DESCRIPTION
**Pull request by jakeman0527**
Add missing closing bracket in attributes file

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JohnRoesler** [comment]
If you'd like to get unit tests to run, you could update the orb to version 2 [example config](https://github.com/sous-chefs/haproxy/blob/master/.circleci/config.yml). The step name changes from `lint` to `delivery` so you'd want to change that in terraform [example here](https://github.com/sous-chefs/terraform-github-org/blob/master/haproxy.tf#L6)

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
Hey,

I'm closing this as your fix seems to have been caught by another PR,

thanks for this though

**Pull request closed without merging**
